name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['1.9.4']

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      - name: Configure PyCall
        run: |
            echo "ENV[\"PYTHON\"] = \"$(which python)\"" >> julia-python.jl
            cat julia-python.jl

      - name: Install dependencies
        env:
          PYTHON: ""  # rebulid PyCall
        run: |
          julia --project -e '
            using Pkg
            Pkg.build("PyCall")  # rebuild PyCall
            Pkg.instantiate()
          '
          
      - name: Run tests
        run: julia --project -e 'using Pkg; Pkg.test()'