name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.9']
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3


      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install matplotlib
        run: pip install matplotlib

      - name: Build Julia package
        uses: julia-actions/julia-buildpkg@v1
      
      - name: Run tests
        uses: julia-actions/julia-runtest@v1