name: Documentation

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      - name: Configure PyCall
        run: |
            echo "ENV[\"PYTHON\"] = \"$(which python)\"" >> julia-python.jl
            cat julia-python.jl
      - name: Install dependencies
        env:
          PYTHON: ""  # rebulid PyCall
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.build("PyCall")  # rebuild PyCall
            Pkg.instantiate()
          '

      # - name: Install dependencies
      #   run: julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      
      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          PYTHON: ""
        run: julia --color=yes --project=docs/ docs/make.jl
